# Generated by Django 4.1.3 on 2022-11-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'PROGRESS'), (2, 'DONE')], db_index=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
    ]
