# Generated by Django 4.1.3 on 2022-11-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_options_data_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
